'use client';
import {FormEvent,useState} from 'react';
import {useMutation,useQuery} from '@tanstack/react-query';
import {useParams,useRouter} from 'next/navigation';
import {trainManagementService,stationManagementService,routeManagementService,journeyManagementService,bookingManagementService} from '@/services/admin/management.service';
import {ErrorState,LoadingState} from '@/components/ui/StatusState';

const errorText=(error:unknown)=>error instanceof Error?error.message:'The operation failed.';
function FormShell({title,children,pending,error,onSubmit}:{title:string;children:React.ReactNode;pending:boolean;error:unknown;onSubmit:(e:FormEvent)=>void}){return <form className="stack" onSubmit={onSubmit}><h1>{title}</h1>{Boolean(error)&&<div className="state state-error" role="alert">{errorText(error)}</div>}{children}<button className="button" disabled={pending}>{pending?'Saving…':'Save'}</button></form>}
export function TrainForm(){const router=useRouter();const [v,set]=useState({trainNumber:'',name:'',description:''});const m=useMutation({mutationFn:()=>trainManagementService.create(v),onSuccess:(r)=>router.push(`/management/trains/${r.id}`)});return <FormShell title="Create train" pending={m.isPending} error={m.error} onSubmit={e=>{e.preventDefault();m.mutate()}}><label className="field"><span>Train number</span><input required maxLength={30} value={v.trainNumber} onChange={e=>set({...v,trainNumber:e.target.value})}/></label><label className="field"><span>Name</span><input required maxLength={150} value={v.name} onChange={e=>set({...v,name:e.target.value})}/></label><label className="field"><span>Description</span><textarea value={v.description} onChange={e=>set({...v,description:e.target.value})}/></label></FormShell>}
export function StationForm({edit=false}:{edit?:boolean}){const {stationId}=useParams<{stationId:string}>();const router=useRouter();const detail=useQuery({queryKey:['management','stations',stationId],queryFn:()=>stationManagementService.get(stationId),enabled:edit});const [draft,setDraft]=useState<Record<string,string>>({});const current={...(detail.data||{}),...draft};const m=useMutation({mutationFn:()=>edit?stationManagementService.update(stationId,draft):stationManagementService.create(draft),onSuccess:(r)=>router.push(`/management/stations/${r.id}`)});if(edit&&detail.isLoading)return <LoadingState/>;return <FormShell title={edit?'Edit station':'Create station'} pending={m.isPending} error={m.error||detail.error} onSubmit={e=>{e.preventDefault();m.mutate()}}>{[['code','Station code'],['name','Station name'],['localName','Local name'],['city','City'],['district','District']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input required={key==='code'||key==='name'} value={current[key]||''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}</FormShell>}
export function RouteForm(){const router=useRouter();const [v,set]=useState({code:'',name:'',startStationId:'',endStationId:'',totalDistanceKm:''});const m=useMutation({mutationFn:()=>routeManagementService.create({...v,totalDistanceKm:Number(v.totalDistanceKm)}),onSuccess:(r)=>router.push(`/management/routes/${r.id}`)});return <FormShell title="Create route" pending={m.isPending} error={m.error} onSubmit={e=>{e.preventDefault();m.mutate()}}>{[['code','Route code'],['name','Route name'],['startStationId','Origin station ID'],['endStationId','Destination station ID'],['totalDistanceKm','Distance (km)']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input required value={(v as any)[key]} onChange={e=>set({...v,[key]:e.target.value})}/></label>)}</FormShell>}
export function JourneyForm(){const router=useRouter();const [v,set]=useState({serviceNumber:'',routeId:'',trainId:'',journeyDate:'',scheduledDepartureAt:'',scheduledArrivalAt:''});const m=useMutation({mutationFn:()=>journeyManagementService.create(v),onSuccess:(r)=>router.push(`/management/journeys/${r.id}`)});return <FormShell title="Create journey" pending={m.isPending} error={m.error} onSubmit={e=>{e.preventDefault();m.mutate()}}>{Object.entries({serviceNumber:'Service number',routeId:'Route ID',trainId:'Train ID',journeyDate:'Journey date',scheduledDepartureAt:'Departure time',scheduledArrivalAt:'Arrival time'}).map(([key,label])=><label className="field" key={key}><span>{label}</span><input required type={key==='journeyDate'?'date':key.includes('At')?'datetime-local':'text'} value={(v as any)[key]} onChange={e=>set({...v,[key]:e.target.value})}/></label>)}</FormShell>}
const services:any={trains:trainManagementService,stations:stationManagementService,routes:routeManagementService,journeys:journeyManagementService,bookings:bookingManagementService};
export function ResourceDetail({resource,id}:{resource:'trains'|'stations'|'routes'|'journeys'|'bookings';id:string}){const q=useQuery({queryKey:['management',resource,id],queryFn:()=>services[resource].get(id)});if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState message={q.error.message} retry={()=>q.refetch()}/>;const data=q.data||{};return <div className="stack"><h1>{data.name||data.serviceNumber||data.bookingReference||data.trainNumber||`${resource.slice(0,-1)} details`}</h1><dl className="detail-grid">{Object.entries(data).filter(([,value])=>value==null||['string','number','boolean'].includes(typeof value)).map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g,' $1')}</dt><dd>{String(value??'—')}</dd></div>)}</dl>{resource==='stations'&&<a className="button" href={`/management/stations/${id}/edit`}>Edit station</a>}</div>}
