'use client';
import Link from 'next/link';
import {useState,ReactNode} from 'react';
import {DataTable,Column} from '@/components/data-table/DataTable';
import {useManagementTrains,useManagementJourneys,useManagementBookings,useManagementPayments,useManagementWaitlist,useManagementAuditLogs} from '@/hooks/api/admin/useManagementLists';
import {useAuthStore} from '@/store/auth.store';
function Shell({title,createHref,search,onSearch,children}:{title:string;createHref?:string;search:string;onSearch:(v:string)=>void;children:ReactNode}){return <div className="stack"><div className="management-title"><h1>{title}</h1>{createHref&&<Link className="button" href={createHref}>Create {title.slice(0,-1).toLowerCase()}</Link>}</div><label className="field"><span>Search</span><input value={search} onChange={e=>onSearch(e.target.value)} placeholder={`Search ${title.toLowerCase()}…`}/></label>{children}</div>}
const badge=(value?:string|boolean)=><span className="badge">{typeof value==='boolean'?(value?'Active':'Inactive'):(value||'—').replaceAll('_',' ')}</span>;
export function TrainManagementView(){const user=useAuthStore(s=>s.user);const [search,setSearch]=useState('');const q=useManagementTrains({search});const c:Column<any>[]=[{key:'number',header:'Train',cell:r=><Link href={`/management/trains/${r.id}`}><b>{r.trainNumber}</b> · {r.name||'Unnamed'}</Link>},{key:'coaches',header:'Coaches',cell:r=>r.coaches?.length??0},{key:'seats',header:'Capacity',cell:r=>(r.coaches||[]).reduce((n:number,x:any)=>n+Number(x.totalSeats||0),0)},{key:'journeys',header:'Journeys',cell:r=>r.journeys?.length??0},{key:'status',header:'Status',cell:r=>badge(r.isActive)}];return <Shell title="Trains" createHref={user?.role==='SUPER_ADMIN'?'/management/trains/new':undefined} search={search} onSearch={setSearch}><DataTable caption="Trains" columns={c} rows={q.data?.items} loading={q.isLoading} error={q.error} retry={()=>q.refetch()} emptyMessage={user?.role==='ADMIN'?'No trains have been assigned to your account. Contact a Super Admin for access.':'No trains found.'}/></Shell>}
export function JourneyManagementListView(){const [search,setSearch]=useState('');const q=useManagementJourneys({search});const c:Column<any>[]=[{key:'service',header:'Service',cell:r=><Link href={`/management/journeys/${r.id}`}><b>{r.serviceNumber}</b></Link>},{key:'date',header:'Date',cell:r=>r.journeyDate},{key:'train',header:'Train',cell:r=>r.train?.trainNumber||'—'},{key:'route',header:'Route',cell:r=>r.route?.name||'—'},{key:'status',header:'Status',cell:r=>badge(r.status)}];return <Shell title="Journeys" createHref="/management/journeys/new" search={search} onSearch={setSearch}><DataTable caption="Journeys" columns={c} rows={q.data?.items} loading={q.isLoading} error={q.error} retry={()=>q.refetch()} emptyMessage="No journeys found."/></Shell>}
export function BookingManagementListView(){const [search,setSearch]=useState('');const q=useManagementBookings({search});const c:Column<any>[]=[{key:'ref',header:'Reference',cell:r=><Link href={`/management/bookings/${r.id}`}><b>{r.bookingReference}</b></Link>},{key:'contact',header:'Passenger',cell:r=>r.contactName},{key:'journey',header:'Journey',cell:r=>r.journey?.serviceNumber||'—'},{key:'amount',header:'Total',cell:r=>`${r.currency} ${r.totalAmount}`},{key:'status',header:'Status',cell:r=>badge(r.status)}];return <Shell title="Bookings" search={search} onSearch={setSearch}><DataTable caption="Bookings" columns={c} rows={q.data?.items} loading={q.isLoading} error={q.error} retry={()=>q.refetch()} emptyMessage="No bookings found."/></Shell>}
export function PaymentManagementView(){const [search,setSearch]=useState('');const q=useManagementPayments({search});const c:Column<any>[]=[{key:'ref',header:'Reference',cell:r=><b>{r.paymentReference}</b>},{key:'booking',header:'Booking',cell:r=>r.booking?.bookingReference||'—'},{key:'method',header:'Method',cell:r=>badge(r.method)},{key:'amount',header:'Amount',cell:r=>`${r.currency} ${r.amount}`},{key:'verification',header:'Bank slip',cell:r=>r.bankSlips?.[0]?.status||'—'},{key:'status',header:'Status',cell:r=>badge(r.status)}];return <Shell title="Payments" search={search} onSearch={setSearch}><Link href="/management/payments/bank-slips">Review pending bank slips</Link><DataTable caption="Payments" columns={c} rows={q.data?.items} loading={q.isLoading} error={q.error} retry={()=>q.refetch()} emptyMessage="No payments found."/></Shell>}
export function WaitlistManagementView(){const [search,setSearch]=useState('');const q=useManagementWaitlist({search});const c:Column<any>[]=[{key:'position',header:'Position',cell:r=>String(r.priorityNumber)},{key:'contact',header:'Contact',cell:r=>r.contactName},{key:'journey',header:'Journey',cell:r=>r.journey?.serviceNumber||'—'},{key:'class',header:'Class',cell:r=>badge(r.requestedCoachClass)},{key:'passengers',header:'Passengers',cell:r=>r.passengerCount},{key:'status',header:'Status',cell:r=>badge(r.status)}];return <Shell title="Waitlist" search={search} onSearch={setSearch}><DataTable caption="Waitlist" columns={c} rows={q.data?.items} loading={q.isLoading} error={q.error} retry={()=>q.refetch()} emptyMessage="The waitlist is empty."/></Shell>}
export function AuditManagementView(){const [search,setSearch]=useState('');const q=useManagementAuditLogs({search});const c:Column<any>[]=[{key:'date',header:'Date',cell:r=>new Date(r.createdAt).toLocaleString()},{key:'actor',header:'Actor',cell:r=>r.user?.fullName||'System'},{key:'action',header:'Action',cell:r=>badge(r.action)},{key:'entity',header:'Entity',cell:r=>`${r.entityType}${r.entityId?` · ${r.entityId}`:''}`},{key:'request',header:'Request',cell:r=>r.requestId||'—',hideOnMobile:true}];return <Shell title="Audit logs" search={search} onSearch={setSearch}><DataTable caption="Audit logs" columns={c} rows={q.data?.items} loading={q.isLoading} error={q.error} retry={()=>q.refetch()} emptyMessage="No audit events found."/></Shell>}
