'use strict';
const { Model } = require('sequelize');
const {
  DataTypes,
  enumType,
  foreignKey,
  id,
  modelOptions,
  requiredDecimal,
  requiredString,
} = require('../database/common-fields');
const BOOKING_STATUS = require('../common/constants/booking-status.constants');
const COACH_CLASS = require('../common/constants/coach-class.constants');
class BookingSeat extends Model {
  static initModel(sequelize) {
    BookingSeat.init(
      {
        id: id(),
        bookingId: foreignKey(),
        bookingPassengerId: { type: DataTypes.UUID },
        journeyId: foreignKey(),
        journeySeatId: foreignKey(),
        seatId: foreignKey(),
        originSequence: { type: DataTypes.INTEGER, allowNull: false },
        destinationSequence: { type: DataTypes.INTEGER, allowNull: false },
        occupiedSegment: {
          type: DataTypes.RANGE(DataTypes.INTEGER),
          set() {
            throw new Error('occupiedSegment is generated by PostgreSQL and is read-only');
          },
        },
        status: enumType(BOOKING_STATUS),
        holdExpiresAt: { type: DataTypes.DATE },
        seatNumberSnapshot: requiredString(20),
        coachNumberSnapshot: requiredString(20),
        coachClassSnapshot: enumType(COACH_CLASS),
        fareAmount: requiredDecimal(10, 2, { validate: { min: 0 } }),
      },
      modelOptions(sequelize, 'booking_seats', { timestamps: true })
    );
    return BookingSeat;
  }
  static associate(models) {
    BookingSeat.belongsTo(models.Booking, { as: 'booking', foreignKey: 'bookingId' });
    BookingSeat.belongsTo(models.BookingPassenger, {
      as: 'passenger',
      foreignKey: 'bookingPassengerId',
    });
    BookingSeat.belongsTo(models.Journey, { as: 'journey', foreignKey: 'journeyId' });
    BookingSeat.belongsTo(models.JourneySeat, { as: 'journeySeat', foreignKey: 'journeySeatId' });
    BookingSeat.belongsTo(models.Seat, { as: 'seat', foreignKey: 'seatId' });
    BookingSeat.hasOne(models.ActiveSeatAllocation, {
      as: 'activeAllocation',
      foreignKey: 'bookingSeatId',
    });
  }
}
module.exports = BookingSeat;
