'use strict';
const SEAT_MAP_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  HELD: 'HELD',
  CONFIRMED: 'CONFIRMED',
  BLOCKED: 'BLOCKED',
  MAINTENANCE: 'MAINTENANCE',
  WAITLIST_OFFERED: 'WAITLIST_OFFERED',
  UNAVAILABLE: 'UNAVAILABLE',
});
module.exports = { SEAT_MAP_STATUS };
