'use strict';
const AuthorizationError = require('../../common/errors/AuthorizationError');
const ValidationError = require('../../common/errors/ValidationError');
const NotFoundError = require('../../common/errors/NotFoundError');
const ROLES = require('../../common/constants/roles.constants');
class AdminTrainAssignmentService {
  constructor({ repository, userRepository, trainRepository, auditService, transactionManager }) { Object.assign(this, { repository, userRepository, trainRepository, auditService, transactionManager }); }
  assertSuperAdmin(actor) { if (actor?.role !== ROLES.SUPER_ADMIN) throw new AuthorizationError('Only a Super Admin can manage train assignments'); }
  async validateAdminTarget(adminId, options={}) { const user=await this.userRepository.findById(adminId,options); if(!user||user.role!==ROLES.ADMIN) throw new ValidationError('The selected user is not an Admin', {code:'INVALID_ADMIN_TARGET'}); return user; }
  async validateTrain(trainId, options={}) { const train=await this.trainRepository.findById(trainId,options); if(!train) throw new NotFoundError('Train not found',{trainId}); return train; }
  assignTrainToAdmin(input) { this.assertSuperAdmin(input.actor); return this.transactionManager.execute(async transaction=>{const options={transaction};await this.validateAdminTarget(input.adminId,options);await this.validateTrain(input.trainId,options);const active=await this.repository.findActiveAssignment(input.adminId,input.trainId,options);if(active)return this.toDto(active);const latest=await this.repository.findLatest(input.adminId,input.trainId,options);const assignment=latest?await this.repository.restoreAssignment(latest,{assignedByUserId:input.actor.id},options):await this.repository.assignTrain({adminUserId:input.adminId,trainId:input.trainId,assignedByUserId:input.actor.id},options);await this.auditService.record({userId:input.actor.id,action:latest?'ADMIN_TRAIN_ASSIGNMENT_RESTORED':'ADMIN_TRAIN_ASSIGNED',entityType:'AdminTrainAssignment',entityId:assignment.id,newValues:{adminId:input.adminId,trainId:input.trainId}},options);return this.toDto(await this.repository.findById(assignment.id,{...options,include:undefined}));}); }
  async assignMultipleTrainsToAdmin(input) { this.assertSuperAdmin(input.actor); const ids=[...new Set(input.trainIds||[])];if(!ids.length)throw new ValidationError('At least one trainId is required');const results=[];for(const trainId of ids)results.push(await this.assignTrainToAdmin({...input,trainId}));return results; }
  revokeTrainFromAdmin(input) { this.assertSuperAdmin(input.actor);return this.transactionManager.execute(async transaction=>{const options={transaction};await this.validateAdminTarget(input.adminId,options);const assignment=await this.repository.revokeTrain(input.adminId,input.trainId,{revokedByUserId:input.actor.id,revocationReason:input.reason||null},options);if(!assignment)throw new NotFoundError('Active train assignment not found',{code:'ADMIN_TRAIN_ASSIGNMENT_NOT_FOUND'});await this.auditService.record({userId:input.actor.id,action:'ADMIN_TRAIN_ASSIGNMENT_REVOKED',entityType:'AdminTrainAssignment',entityId:assignment.id,newValues:{adminId:input.adminId,trainId:input.trainId,reason:input.reason}},options);return this.toDto(assignment);}); }
  async revokeAllTrainsFromAdmin(input){this.assertSuperAdmin(input.actor);await this.validateAdminTarget(input.adminId);return this.repository.revokeAllAdminTrains(input.adminId,{revokedByUserId:input.actor.id,revocationReason:input.reason||null});}
  getAdminAssignedTrains(input){this.assertSuperAdmin(input.actor);return this.repository.findAdminTrainAssignments(input.adminId).then(rows=>rows.map(row=>this.toDto(row)));}
  getTrainAssignedAdmins(input){this.assertSuperAdmin(input.actor);return this.repository.findTrainAdminAssignments(input.trainId).then(rows=>rows.map(row=>this.toDto(row)));}
  getAdminTrainAssignmentHistory(input){this.assertSuperAdmin(input.actor);return this.repository.getAssignmentHistory(input.adminId).then(rows=>rows.map(row=>this.toDto(row)));}
  toDto(record){const v=record.toJSON?record.toJSON():record;return {id:v.id,admin:v.admin&&{id:v.admin.id,fullName:v.admin.fullName,email:v.admin.email,role:v.admin.role},train:v.train&&{id:v.train.id,trainNumber:v.train.trainNumber,name:v.train.name,status:v.train.isActive?'ACTIVE':'INACTIVE'},assignedBy:v.assignedBy&&{id:v.assignedBy.id,fullName:v.assignedBy.fullName},isActive:v.isActive,assignedAt:v.assignedAt,revokedAt:v.revokedAt,revocationReason:v.revocationReason};}
}
module.exports=AdminTrainAssignmentService;
