'use strict';
const AuthorizationError=require('../../common/errors/AuthorizationError');
const ValidationError=require('../../common/errors/ValidationError');
const NotFoundError=require('../../common/errors/NotFoundError');
class StaffStationAssignmentService{
 constructor(deps){Object.assign(this,deps)}
 assertSuperAdmin(actor){if(actor?.role!=='SUPER_ADMIN')throw new AuthorizationError('Only a Super Admin can manage station assignments')}
 async validateStaffTarget(id,options={}){const user=await this.userRepository.findById(id,options);if(!user||user.role!=='STAFF')throw new ValidationError('The selected user is not a Staff user',{code:'INVALID_STAFF_TARGET'});return user}
 async validateStation(id,options={}){const station=await this.stationRepository.findById(id,options);if(!station)throw new NotFoundError('Station not found',{stationId:id});return station}
 assignStationToStaff(input){this.assertSuperAdmin(input.actor);return this.transactionManager.execute(async transaction=>{const options={transaction};await this.validateStaffTarget(input.staffId,options);await this.validateStation(input.stationId,options);const active=await this.repository.findActiveAssignment(input.staffId,input.stationId,options);if(active)return this.toDto(active);const latest=await this.repository.findLatest(input.staffId,input.stationId,options);const row=latest?await this.repository.restoreAssignment(latest,{assignedByUserId:input.actor.id},options):await this.repository.assignStation({staffUserId:input.staffId,stationId:input.stationId,assignedByUserId:input.actor.id},options);await this.auditService.record({userId:input.actor.id,action:latest?'STAFF_STATION_ASSIGNMENT_RESTORED':'STAFF_STATION_ASSIGNED',entityType:'StaffStation',entityId:row.id,newValues:{staffId:input.staffId,stationId:input.stationId}},options);return this.toDto(row)})}
 async assignMultipleStationsToStaff(input){this.assertSuperAdmin(input.actor);const ids=[...new Set(input.stationIds||[])];if(!ids.length)throw new ValidationError('At least one stationId is required');const result=[];for(const stationId of ids)result.push(await this.assignStationToStaff({...input,stationId}));return result}
 revokeStationFromStaff(input){this.assertSuperAdmin(input.actor);return this.transactionManager.execute(async transaction=>{const options={transaction};const row=await this.repository.revokeStation(input.staffId,input.stationId,{revokedByUserId:input.actor.id,revocationReason:input.reason||null},options);if(!row)throw new NotFoundError('Active station assignment not found',{code:'STAFF_STATION_ASSIGNMENT_NOT_FOUND'});await this.auditService.record({userId:input.actor.id,action:'STAFF_STATION_ASSIGNMENT_REVOKED',entityType:'StaffStation',entityId:row.id,newValues:{staffId:input.staffId,stationId:input.stationId,reason:input.reason}},options);return this.toDto(row)})}
 async revokeAllStationsFromStaff(input){this.assertSuperAdmin(input.actor);await this.validateStaffTarget(input.staffId);return this.repository.revokeAllStaffStations(input.staffId,{revokedByUserId:input.actor.id,revocationReason:input.reason||null})}
 getStaffAssignedStations(input){this.assertSuperAdmin(input.actor);return this.repository.findStaffStationAssignments(input.staffId).then(rows=>rows.map(row=>this.toDto(row)))}
 getStationAssignedStaff(input){this.assertSuperAdmin(input.actor);return this.repository.findStationStaffAssignments(input.stationId).then(rows=>rows.map(row=>this.toDto(row)))}
 getStaffStationAssignmentHistory(input){this.assertSuperAdmin(input.actor);return this.repository.getAssignmentHistory(input.staffId).then(rows=>rows.map(row=>this.toDto(row)))}
 toDto(row){const v=row.toJSON?row.toJSON():row;return{id:v.id,staff:v.staff&&{id:v.staff.id,fullName:v.staff.fullName,email:v.staff.email,role:v.staff.role},station:v.station&&{id:v.station.id,code:v.station.code,name:v.station.name,status:v.station.isActive?'ACTIVE':'INACTIVE'},assignedBy:v.assignedBy&&{id:v.assignedBy.id,fullName:v.assignedBy.fullName},isActive:v.isActive,assignedAt:v.assignedAt,revokedAt:v.revokedAt,revocationReason:v.revocationReason}}
}
module.exports=StaffStationAssignmentService;
