'use strict';
const AuthorizationError=require('../../common/errors/AuthorizationError');
class StationScopeAuthorizationService{
 constructor({assignmentRepository,sequelize}){this.assignmentRepository=assignmentRepository;this.sequelize=sequelize||require('../../database/sequelize')}
 getAccessibleStationIds(actor,options={}){if(actor?.role==='SUPER_ADMIN')return Promise.resolve(null);if(actor?.role!=='STAFF')return Promise.resolve([]);return this.assignmentRepository.findAssignedStationIds(actor.id,options)}
 async canAccessStation(actor,stationId,options={}){if(actor?.role==='SUPER_ADMIN')return true;if(actor?.role!=='STAFF')return false;return this.assignmentRepository.isStaffAssignedToStation(actor.id,stationId,options)}
 async assertStationAccess(actor,stationId,options={}){if(!await this.canAccessStation(actor,stationId,options))throw new AuthorizationError('This station has not been assigned to your account.',{code:'STATION_ACCESS_DENIED',stationId});return true}
 async relatedStationIds(kind,id,options={}){const sql={journey:'SELECT station_id FROM journey_stations WHERE journey_id=:id',booking:'SELECT js.station_id FROM bookings b JOIN journey_stations js ON js.id IN (b.origin_journey_station_id,b.destination_journey_station_id) WHERE b.id=:id',passenger:'SELECT js.station_id FROM booking_passengers bp JOIN bookings b ON b.id=bp.booking_id JOIN journey_stations js ON js.id IN (b.origin_journey_station_id,b.destination_journey_station_id) WHERE bp.id=:id'}[kind];const [rows]=await this.sequelize.query(sql,{...options,replacements:{id}});return rows.map(row=>row.station_id)}
 async assertRelated(actor,kind,id,options={}){if(actor?.role==='SUPER_ADMIN')return true;if(actor?.role!=='STAFF')throw new AuthorizationError();const [assigned,related]=await Promise.all([this.getAccessibleStationIds(actor,options),this.relatedStationIds(kind,id,options)]);if(!related.some(id=>assigned.includes(id)))throw new AuthorizationError(kind==='booking'?'This booking is not related to one of your assigned stations.':`This ${kind} is outside your assigned station scope.`,{code:'STATION_ACCESS_DENIED'});return true}
 canManageStation(...args){return this.canAccessStation(...args)} canAccessJourney(actor,id,options){return this.assertRelated(actor,'journey',id,options)} canAccessBooking(actor,id,options){return this.assertRelated(actor,'booking',id,options)} canAccessPassenger(actor,id,options){return this.assertRelated(actor,'passenger',id,options)} canAccessSeatMap(actor,id,options){return this.assertRelated(actor,'journey',id,options)} canCreateBooking(...args){return this.canAccessStation(...args)} canAccessStationAnalytics(...args){return this.canAccessStation(...args)} canAccessStationOperations(...args){return this.canAccessStation(...args)}
}
module.exports=StationScopeAuthorizationService;
