'use strict';
const express=require('express');
const authorize=require('../common/middleware/authorize.middleware');
const requirePasswordChanged=require('../common/middleware/require-password-change.middleware');
const asyncHandler=require('../common/utils/async-handler');
const apiResponse=require('../common/utils/api-response');
const ManagementService=require('../modules/management/management.service');
const scopeMiddleware=require('../common/middleware/authorize-train-scope.middleware');
const clean=(record)=>record?.toJSON?.()||record;
module.exports=(services)=>{const router=express.Router();const management=new ManagementService();const scope=services.trainScopeAuthorizationService;const guard=scopeMiddleware(scope);router.use(requirePasswordChanged,authorize('ADMIN'));
 const scopedList=(resource)=>asyncHandler(async(req,res)=>{const ids=await scope.getAccessibleTrainIds(req.user);res.json(apiResponse.success(await management.list(resource,{...req.query,accessibleTrainIds:ids})));});
 for(const resource of ['trains','journeys','bookings','payments','waitlist'])router.get(`/${resource}`,scopedList(resource));
 router.get('/trains/:trainId',guard.authorizeTrainParam(),asyncHandler(async(req,res)=>res.json(apiResponse.success(clean(await services.trainService.getTrainConfiguration(req.params.trainId))))));
 router.patch('/trains/:trainId',guard.authorizeTrainParam(),asyncHandler(async(req,res)=>res.json(apiResponse.success(clean(await services.trainService.updateTrain(req.params.trainId,req.body))))));
 router.get('/trains/:trainId/coaches',guard.authorizeTrainParam(),asyncHandler(async(req,res)=>{const train=await services.trainService.getTrainConfiguration(req.params.trainId);res.json(apiResponse.success((train.coaches||[]).map(clean)));}));
 router.post('/trains/:trainId/coaches',guard.authorizeTrainParam(),asyncHandler(async(req,res)=>res.status(201).json(apiResponse.success(clean(await services.coachService.createCoach({...req.body,trainId:req.params.trainId}))))));
 router.patch('/trains/:trainId/coaches/:coachId',guard.authorizeTrainParam(),asyncHandler(async(req,res)=>res.json(apiResponse.success(clean(await services.coachService.updateCoach(req.params.coachId,req.body))))));
 router.post('/trains/:trainId/coaches/:coachId/seats/generate',guard.authorizeTrainParam(),asyncHandler(async(req,res)=>res.status(201).json(apiResponse.success((await services.coachService.generateSeats(req.params.coachId,req.body)).map(clean)))));
 router.get('/journeys/:journeyId',guard.authorizeJourneyTrainScope(),asyncHandler(async(req,res)=>res.json(apiResponse.success(clean(await services.journeyService.getJourneySnapshot(req.params.journeyId))))));
 router.post('/journeys',asyncHandler(async(req,res)=>{await scope.assertTrainAccess(req.user,req.body.trainId);res.status(201).json(apiResponse.success(clean(await services.journeyService.createJourney(req.body))));}));
 router.patch('/journeys/:journeyId',guard.authorizeJourneyTrainScope(),asyncHandler(async(req,res)=>res.json(apiResponse.success(clean(await services.journeyService.updateJourney(req.params.journeyId,req.body))))));
 router.post('/journeys/:journeyId/delay',guard.authorizeJourneyTrainScope(),asyncHandler(async(req,res)=>res.json(apiResponse.success(clean(await services.journeyService.delayJourney(req.params.journeyId,Number(req.body.delayMinutes),{reason:req.body.reason}))))));
 router.post('/journeys/:journeyId/cancel',guard.authorizeJourneyTrainScope(),asyncHandler(async(req,res)=>res.json(apiResponse.success(clean(await services.journeyService.cancelJourney(req.params.journeyId))))));
 router.get('/bookings/:bookingId',guard.authorizeBookingTrainScope(),asyncHandler(async(req,res)=>res.json(apiResponse.success(await management.detail('bookings',req.params.bookingId)))));
 return router;};
